### ISSUE TITLE
ipython notebook does not work?

### ISSUE THREAD

**Issue by biboyanov** [thomasbkahn/step-detect#6]
When I try to run it within Github it thinks for a bit then complains "Sorry, something went wrong. Reload?"  I tried downloading and converting to Python (via Juniper) so I can see the usage example and it produces a lengthy error report

`D:\xxx\Documents\python\Step detect>ipython nbconvert --to=python step_detect_demo.ipynb
[TerminalIPythonApp] WARNING | Subcommand `ipython nbconvert` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter nbconvert` in the future
[NbConvertApp] Converting notebook step_detect_demo.ipynb to python
Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\ipython-script.py", line 10, in <module>
    sys.exit(start_ipython())
  File "C:\Anaconda2\lib\site-packages\IPython\__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "C:\Anaconda2\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Anaconda2\lib\site-packages\IPython\terminal\ipapp.py", line 351, in start
    return self.subapp.start()
  File "C:\Anaconda2\lib\site-packages\nbconvert\nbconvertapp.py", line 337, in start
    self.convert_notebooks()
  File "C:\Anaconda2\lib\site-packages\nbconvert\nbconvertapp.py", line 507, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "C:\Anaconda2\lib\site-packages\nbconvert\nbconvertapp.py", line 478, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "C:\Anaconda2\lib\site-packages\nbconvert\nbconvertapp.py", line 407, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "C:\Anaconda2\lib\site-packages\nbconvert\exporters\exporter.py", line 178, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "C:\Anaconda2\lib\site-packages\nbconvert\exporters\exporter.py", line 196, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "C:\Anaconda2\lib\site-packages\nbformat\__init__.py", line 141, in read
    return reads(fp.read(), as_version, **kwargs)
  File "C:\Anaconda2\lib\site-packages\nbformat\__init__.py", line 74, in reads
    nb = reader.reads(s, **kwargs)
  File "C:\Anaconda2\lib\site-packages\nbformat\reader.py", line 58, in reads
    nb_dict = parse_json(s, **kwargs)
  File "C:\Anaconda2\lib\site-packages\nbformat\reader.py", line 17, in parse_json
    raise NotJSONError(("Notebook does not appear to be JSON: %r" % s)[:77] + "...")
NotJSONError: Notebook does not appear to be JSON: u'\n\n\n\n\n\n<!DOCTYPE html>\n<html lan...

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True`

**Comment by biboyanov** [comment]
Started working a bit later, not sure why, did not change anything on my end.  Closing issue
